application: oi-automatons
version: 9
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "2d"

handlers:
  
- url: /(.*\.(gif|png|jpg|ico))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico))
  http_headers:
    Cache-Control: public
    expiration: "12d"
    
- url: /(.*\.(js|css|xml))
  static_files: \1
  upload: (.*\.(js|css|xml))
  http_headers:
    Cache-Control: public
    expiration: "3d"

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
