application: oi-automatons
version: 16
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css))
  http_headers:
    Cache-Control: public
    expiration: "12d"

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /test.txt
  static_files: test.txt
  upload: test.txt
  
- url: /google5c9cacb3aed3ae1a.html
  static_files: google5c9cacb3aed3ae1a.html
  upload: 

- url: /partials
  static_dir: partials

- url: /app
  static_dir: app

- url: .*
  script: main.app

libraries:
- name: PIL
  version: latest
