application: oi-automatons
version: 8
runtime: python27
api_version: 1
threadsafe: false

default_expiration: "2d"

handlers:

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
  
- url: /Images
  static_dir: Images
  http_headers:
    Cache-Control: public
    expiration: "7d"

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  http_headers:
    Cache-Control: public
    expiration: "14d"
    
- url: /css
  static_dir: css
  http_headers:
    Cache-Control: public
    expiration: "1d 12h"

- url: /Scripts
  static_dir: Scripts
  http_headers:
    Cache-Control: public
    expiration: "3d"
